name: 'Install OSX dependencies'
description: 'Install OSX dependencies'
inputs:
  compiler_homebrew_package:
    description: "Which compiler package to install from homebrew"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        brew install ninja macfuse libomp ${{inputs.compiler_homebrew_package}}
        pip3 install conan
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default
