name: 'Install local dependencies'
description: 'Install local dependencies'
runs:
  using: "composite"
  steps:
    - name: Install local dependencies
      shell: bash
      run: |
        set -v
        # TODO Cache these dependencies for faster runtime

        export NUMCORES=`nproc` && if [ ! -n "$NUMCORES" ]; then export NUMCORES=`sysctl -n hw.ncpu`; fi
        echo Using $NUMCORES cores

        echo Download range-v3
        cd ~
        wget https://github.com/ericniebler/range-v3/archive/0.11.0.tar.gz -O range-v3-0.11.0.tar.gz
        if [ $(sha512sum range-v3-0.11.0.tar.gz | awk '{print $1;}') == "9d6cdcbc1e50104206ba731c3bdc9aab3acfcf69cd83f0e0b4de18b88df2a9e73d64e55638421768d4433c542b6619f6e5af6b17cccd3090cf8b4d4efe9863e4" ]; then
          echo Correct sha512sum
        else
          echo Wrong sha512sum
          sha512sum range-v3-0.11.0.tar.gz
          exit 1
        fi
        tar -xvf range-v3-0.11.0.tar.gz
        cd range-v3-0.11.0/

        echo Install range-v3
        mkdir build
        cd build
        cmake .. -DRANGES_HAS_WERROR=off -DRANGE_V3_EXAMPLES=off -DRANGE_V3_TESTS=off
        make -j$NUMCORES
        sudo make install
        cd ~
        rm -rf range-v3-0.11.0
        rm range-v3-0.11.0.tar.gz

        echo Download spdlog
        cd ~
        wget https://github.com/gabime/spdlog/archive/v1.8.5.tar.gz -O spdlog.tar.gz
        if [ $(sha512sum spdlog.tar.gz | awk '{print $1;}') == "77cc9df0c40bbdbfe1f3e5818dccf121918bfceac28f2608f39e5bf944968b7e8e24a6fc29f01bc58a9bae41b8892d49cfb59c196935ec9868884320b50f130c" ]; then
          echo Correct sha512sum
        else
          echo Wrong sha512sum
          sha512sum spdlog.tar.gz
          exit 1
        fi
        tar -xvf spdlog.tar.gz
        rm spdlog.tar.gz
        cd spdlog-1.8.5

        echo Install spdlog
        mkdir build
        cd build
        cmake ..
        make -j$NUMCORES
        sudo make install

        echo Download boost
        cd ~
        wget -O boost.tar.bz2 https://sourceforge.net/projects/boost/files/boost/1.75.0/boost_1_75_0.tar.bz2/download
        if [ $(sha512sum boost.tar.bz2 | awk '{print $1;}') == "d86f060245e98dca5c7f3f831c98ea9ccbfa8310f20830dd913d9d4c939fbe7cb94accd35f1128e7c4faf6c27adb6f4bb54e5477a6bde983dfc7aa33c4eed03a" ]; then
          echo Correct sha512sum
        else
          echo Wrong sha512sum
          sha512sum boost.tar.bz2
          exit 1
        fi
        echo Extracting boost
        tar -xf boost.tar.bz2
        rm boost.tar.bz2
        cd boost_1_75_0

        echo Install boost
        ./bootstrap.sh --with-libraries=filesystem,system,thread,chrono,program_options
        sudo ./b2 link=shared cxxflags=-fPIC --prefix=/usr -d0 -j$NUMCORES install
