name: 'Setup Windows'
description: 'Setup Windows'
runs:
  using: "composite"
  steps:
    - name: Install Windows dependencies
      shell: bash
      run: |
        set -v
        set -e
        choco install -y ninja wget ccache
        wget https://github.com/dokan-dev/dokany/releases/download/v2.3.1.1000/Dokan_x64.msi
        if [ $(sha512sum Dokan_x64.msi | awk '{print $1;}') == "87f3dee76606cddcb60ede11c699fae430194687e10fa4c1c3d76822893020f092fdb8ec7b2de80626886870f789d9bd0b70facc92120a65d4164063e4c56708" ]; then
          echo Correct sha512sum
        else
          echo Wrong sha512sum
          sha512sum Dokan_x64.msi
          exit 1
        fi
        echo Installing DokanY
        msiexec "-i" "Dokan_x64.msi" "-norestart" "-passive" INSTALLDEVFILES=1
        # msiexec "-i" "Dokan_x64.msi" "-norestart" "-passive" "-lv*!" dokan-install-logfile.txt INSTALLDEVFILES=1
        # cat dokan-install-logfile.txt
        echo Installing DokanY finished
