.\" cryfs-unmount(1) man page
.
.TH cryfs-unmount 1
.
.
.
.SH NAME
cryfs-unmount \- unmount a CryFS volume
.
.
.
.SH SYNOPSIS
.B cryfs-unmount
[\fB\-h\fR]
[\fB\--version\fR]
.I mountpoint
.
.
.
.SH DESCRIPTION
.
Unmount a mounted
.B CryFS
volume.
.PP
.
.
.SH OPTIONS
.
.TP
\fB\-h\fR, \fB\-\-help\fR
.
Show a help message containing short descriptions for all options.
.
.
.TP
\fB\-\-verson\fR
.
Show the version of the installed
.B CryFS
package.
.
.
.
.
.SH SEE ALSO
.
.BR mount.fuse (1),
.BR fusermount (1),
.BR cryfs (1)
.PP
.
For more information about the design of CryFS, visit
.B https://www.cryfs.org
.PP
.
Visit the development repository at
.B https://github.com/cryfs/cryfs
for the source code and the full list of contributors to CryFS.
.
.
.
.SH AUTHORS
.
CryFS was created by Sebastian Messmer and contributors.
