#!/bin/bash
# This script is called after the cryfs .deb package is uninstalled.
# It removes the package source that was used to get automatic updates.

set -e

get_apt_config () {
  apt-config dump|grep "$1 "|sed -e "s/^$1\ \"\([^\"]*\)\"\;/\1/g"
}

sources_list_dir () {
  root=$(get_apt_config "Dir")
  etc=$(get_apt_config "Dir::Etc")
  sourceparts=$(get_apt_config "Dir::Etc::sourceparts")
  echo $root$etc$sourceparts
}

remove_repository () {
  dir=$(sources_list_dir)
  rm -f $dir/cryfs.list
}

remove_key () {
  # Don't fail if key was already removed
  apt-key rm 549E65B2 2>&1 > /dev/null || true
}

case "$1" in
    purge)
        remove_repository
        remove_key
    ;;

    abort-install|abort-upgrade|remove|upgrade|failed-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

set +e

exit 0
